### PR TITLE
Annotate types as optional

### PR DESCRIPTION
**Pull request by dsaxton**
## Summary

Hi all, typing nitpick here but I noticed there are a lot of optional types that are not annotated as such so I thought I'd start doing that. This doesn't cover them all, but if this is a change you would like to make I can fix some more (some function signatures are only partially fixed in this PR at the moment, for example).

## Importance

Would allow for better inferences by tools like mypy.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by jlowin** [comment]
Mypy automatically infers the `Optional` typing when a default is `None`, but I just learned that behavior is being deprecated: https://github.com/python/mypy/issues/9091

**Comment by dsaxton** [comment]
> Mypy automatically infers the `Optional` typing when a default is `None`, but I just learned that behavior is being deprecated: [python/mypy#9091](https://github.com/python/mypy/issues/9091)

Ah, I didn't know that, thanks! I'll close then, since this is a lot of extra boilerplate.

**Comment by jlowin** [comment]
Sorry @dsaxton, I didn't mean to write that to shut down the PR - I was going to share it with you in case you didn't know, but then learned it's now an unsupported behavior! I think it raises a good question of the degree to which we want to support mypy, as currently Server does not enforce mypy semantics (though Core does).

**Comment by dsaxton** [comment]
> Sorry @dsaxton, I didn't mean to write that to shut down the PR - I was going to share it with you in case you didn't know, but then learned it's now an unsupported behavior! I think it raises a good question of the degree to which we want to support mypy, as currently Server does not enforce mypy semantics (though Core does).

No worries, let me know if you'd like to reopen. It does seem though that relying instead on the `--implicit-optional` flag may be the easier / preferred approach (depending on how pedantic we want to be about what the "correct" type is).

**Pull request closed without merging**
