### PR TITLE
upgrade to hasura2.0

### PR DESCRIPTION
**Pull request by jakekaplan**
## Summary

Upgrades Hasura to v.2.0.9

## Importance
Prefect Server is on a very old version of Hasura. Upgrading to v.2.0.9 allows it to keep up with current functionality.

## Checklist

This PR:

~~- [ ] adds new tests (if appropriate)~~
- [x] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by cicdw** [comment]
This LGTM -- we just need to confirm that the metadata that Hasura manages within the DB isn't negatively affected by this change; we'll need to reference the section titled "Deprecation of database specific env vars" in [the upgrade guide](https://hasura.io/docs/latest/graphql/core/guides/upgrade-hasura-v2.html).

I think one way of approaching this is to start Server connected to a persistent database with the older version of Hasura, and then do the Hasura upgrade only (with the same DB) and confirm all works as expected

**Comment by jakekaplan** [comment]
@cicdw I tested this with a persistent postgres on my local machine. Hasura will manage the hdb_catalog schema itself. It effectively removes the tables used for v1 Hasura and populates v2 Hasura tables. Really what it does it shoves all that table information into a single json blob in a `hdb_metadata` table. Which exactly you get out when you export the metadata table via the UI

**Comment by jakekaplan** [comment]
@cicdw I updated the yaml to "hasura config verion 3" to keep it consistent with cloud. We don't actually set anything different here (like max_connections) in cloud, but this allows for it if we want to.

**Comment by BitTheByte** [comment]
@cicdw this change seems ok, I tested the server's functionality using my local environment and everything apparently is working fine. I'd love to see it moves to release as I'm also using Hasura for my deployment and it would be easier to just have one instance instead of two

**Comment by cicdw** [comment]
Thanks for testing @BitTheByte , we really appreciate that!

**Review by cicdw — APPROVED** [review]
LGTM

**Pull request merged**
