### PR TITLE
fix missing server configs on hasura and towel deployments

### PR DESCRIPTION
**Pull request by gabriel-milan**
## Summary
As I've spoken to @kvnkho [on Slack](https://prefect-community.slack.com/archives/CL09KU1K7/p1644943315764649), the Prefect Server configurations set on the `values.yaml` file are still missing on both Hasura and Towel deployments.

## Importance
This fixes misconfiguration for Hasura and Towel.

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by madkinsz** [comment]
Hi! We can add this to the towel service, which indeed does consume some of the config values for Prefect Server. However, Hasura does not use our config so I don't see what including the environment variables there would do. Is there a specific issue that's resolving for you?

**Comment by gabriel-milan** [comment]
That's correct. Only Towel needs the update for my use case. I just thought that maybe it was also missing for Hasura, but if it's not used, I think that it's fine.

**Comment by madkinsz** [comment]
> That's correct. Only Towel needs the update for my use case. I just thought that maybe it was also missing for Hasura, but if it's not used, I think that it's fine.

Yeah their container won't do anything with those variables so we probably shouldn't include them.

**Comment by gabriel-milan** [comment]
> we probably shouldn't include them

I've just removed it, thanks for saying that!

**Comment by madkinsz** [comment]
@gabriel-milan thanks! Looks like you'll just need to get up to date with the `master` branch now.

**Comment by gabriel-milan** [comment]
does it seem correct? i'm not sure

**Review by madkinsz — APPROVED** [review]
Yep! Thanks!

**Pull request merged**
