### PR TITLE
Expose database upgrade errors during infra start

### PR DESCRIPTION
**Pull request by madkinsz**
## Summary

An error during database upgrade is hidden with a message "Database is not ready..."

## Changes

- Only displays that the database is not ready when the exception is a refused connection
- Other exceptions are displayed and reraised

Example output
```
prefect-3.7 ❯ prefect-server dev infrastructure
Pulling postgres ... done
Pulling hasura   ... done
Database upgrade encountered fatal error:

(psycopg2.OperationalError) FATAL:  role "prefect" does not exist

(Background on this error at: http://sqlalche.me/e/13/e3q8)

Exception caught; killing services (press ctrl-C to force)

... full traceback
```

## Importance

Silencing exceptions during database setup makes it challenging to troubleshoot

## Checklist

This PR:

- [ ] adds new tests (if appropriate)
- [x] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by madkinsz** [comment]
I'm still unsure on the scope of `changes/` and there are no CLI tests. Let me know if either is appropriate.

**Comment by madkinsz** [comment]
I'm still unsure on the scope of `changes/` and there are no CLI tests. Let me know if either is appropriate.

**Comment by joshmeek** [comment]
@madkinsz I think a changes entry is still helpful here 👍

**Review by joshmeek — APPROVED** [review]

**Review by cicdw — APPROVED** [review]
LGTM

In general, think of the `changes/` of server as a bookkeeping system so we know what we've released and not released.  Because of that, pretty much any behavioral or UX change is worthy of mention IMO

**Pull request merged**
