### PR TITLE
Increase number of max scheduled runs to 50

### PR DESCRIPTION
**Pull request by znicholasbrown**
## Summary

Increases the max number of scheduled runs from 10 -> 50

## Importance

Gives the scheduler some breathing room when running over large numbers of flows.

## Checklist

This PR:

- [cc @cicdw] adds new tests (if appropriate)
- [ ] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by bouke-sf** [comment]
#281 makes this value configurable.

**Comment by madkinsz** [comment]
Note that this was left open because raising it to 50 introduced some other issues, you may want to avoid changing the value to be too large @bouke-sf

**Comment by bouke-sf** [comment]
Thanks for mentioning! Were the issues specifically caused by 1 flow with 50 runs, or just 50 concurrent runs in general?

**Comment by madkinsz** [comment]
I don't remember, actually :) cc @znicholasbrown if you remember what issues arose

**Comment by znicholasbrown** [comment]
@bouke-sf - the primary issue is just related to scheduler performance; the scheduler will need to loop through every flow in the db and can back up if it's not able to complete that loop before it's called again; this should only impact pretty large deployments though. Love the configurability!

**Pull request closed without merging**
