### PR TITLE
Dockerfile Refactoring and Improvements

### PR DESCRIPTION
**Pull request by gabrielcalderon**
## Summary
* Reduce overall size of final docker image by using less layers.
* Added default UTF-8 locale to system.
* Avoid having pip cache by using --no-install-cache for Prefect Core library.
* Added comments to Dockerfile
* Shouldn't affect CI process since build arguments were left the same
* Changed base image from **python:3.7** to **python:3.7-slim**

## Changes
* Overall image size of latest tag uncompressed was reduced from **1.01 GB** to **356 MB**, a _decrease_ of **64.7%**.
* Added default locale UTF-8
* Remove **git** after installing Prefect and Prefect Server.
* Added **PREFECT_SERVER_VERSION** build argument to Dockerfile. Defaults to **master**
* Added **PYTHON_VERSION** build argument to Dockerfile. Defaults to **3.7**
* Added image labels.
* Both **PREFECT_VERSION** and **PREFECT_SERVER_VERSION** now default to "master".

## Future work
* The current CI process should be updated to pass the Prefect Server version using **PREFECT_SERVER_VERSION** to the docker build. The current Dockerfile defaults to **master** for both Prefect and Prefect Server, unless an argument is passed.

* I also noticed that services like **Towel**, **GraphQL**, etc are being run directly by calling the code instead of using prefect-server services. Adding back these sources files increase the final image size by **20MB**.

* Currently towel is started via:
```
python src/prefect-server/services/towel/__main__.py
```
* Instead of: 
```
prefect-server services towel
```

Fixing this is beyond this PR and the changes will break the [docker-compose.yml](https://github.com/PrefectHQ/prefect/blob/master/src/prefect/cli/docker-compose.yml) files used to start Prefect.

## Importance
* Reduce network usage when downloading image.
* Reduce storage usage when using Prefect Docker Image.
* New Dockerfile is similar to PrefectHQ/Prefect.

## Checklist

This PR:

- [x ] adds new tests (if appropriate)
- [x ] adds a change file in the `changes/` directory (if appropriate)

### CODE REVIEW

**Comment by cicdw** [comment]
Hi @gabrielcalderon - is the pull bot something you have configured?  We don't use that bot but it appears to have auto-closed your PR

**Comment by gabrielcalderon** [comment]
@cicdw I do and it delete all my changes. Great...

**Comment by cicdw** [comment]
Hopefully you still have them locally!!

**Comment by gabrielcalderon** [comment]
I do, i'm going to recommit them in a separate branch and open a new PR. Pull Bot will override my master branch with any changes from upstream.

**Comment by gabrielcalderon** [comment]
@cicdw New PR was open https://github.com/PrefectHQ/server/pull/60

**Pull request closed without merging**
